[package]
name = "ClusterNoodle"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "5.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"]}
serde_yaml = "0.9"
